name: Daily Key & Shortlink

on:
  schedule:
    - cron: '0 0 * * *' # chạy mỗi 0h00 UTC
  workflow_dispatch:

jobs:
  generate_key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Generate daily key
        run: |
          import json, random, string, datetime, urllib.parse, requests, os

          # Sinh key ngẫu nhiên
          key_prefix = "KhanhMG-"
          key_random = ''.join(random.choices(string.ascii_letters + string.digits, k=12))
          key = key_prefix + key_random

          # Lưu key hôm nay
          data = {"key": key, "date": str(datetime.date.today())}
          with open("key_today.json", "w") as f:
              json.dump(data, f)

          # Rút gọn link YeuMoney
          yeu_api_token = "769323f441b8e15f97640d5d716bd50098b884b4328a599152cbcf1519af4b84"
          original_url = f"https://raw.githubusercontent.com/{os.environ['GITHUB_REPOSITORY']}/main/key_today.json"
          api_url = f"https://yeumoney.com/QL_api.php?token={yeu_api_token}&url={urllib.parse.quote(original_url)}&format=json"

          try:
              res = requests.get(api_url, timeout=20).json()
              shortlink = res.get("shortenedUrl", "")
          except:
              shortlink = ""

          with open("yeu_shortlink.txt", "w") as f:
              f.write(shortlink)

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add key_today.json yeu_shortlink.txt
          git commit -m "Update key và shortlink"
          git push
