name: Daily Key + YeuMoney Shortlink

on:
  schedule:
    - cron: '0 0 * * *'  # chạy 0h00 UTC mỗi ngày
  workflow_dispatch:     # cho phép chạy thủ công

jobs:
  generate-and-short:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate key, create shortlink, write files
        env:
          YEUMONEY_API_TOKEN: ${{ secrets.YEUMONEY_API_TOKEN }}
          INDEX_HTML_URL: "https://khanhnek5.github.io/NguyenVuKhanh/index.html"
        run: |
          python3 scripts/generate_key.py

      - name: Commit & push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add key_today.json yeu_shortlink.txt redirect.html || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update daily key & YeuMoney shortlink [skip ci]"
            git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
