name: Generate daily key and YeuMoney shortlink

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate_key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run generator
        run: python generate.py
        env:
          YEUMONEY_API_TOKEN: ${{ secrets.YEUMONEY_API_TOKEN }}
          INDEX_HTML_URL: "https://khanhnek5.github.io/NguyenVuKhanh/index.html"

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add key.json shortlink.json redirect.html
          git commit -m "Auto-update daily key and shortlink" || echo "No changes"
          git push
